In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [2]:
# Loading the dataset

data=pd.read_csv("/Users/akash/Desktop/ML Projects/ANN Classification Project/Churn Predictions/Churn_Modelling.csv")

In [3]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [10]:
# Preprocessing the data
# droping the irrelevent columns


data=data.drop(['RowNumber','CustomerId','Surname'], axis=1, errors='ignore')

In [11]:
data.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [12]:
#Encoding Categorical variables

label_encoder_Gender=LabelEncoder()
data['Gender']=label_encoder_Gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [14]:
# One Hot encoder for Geography column
from sklearn.preprocessing import OneHotEncoder
ohe_geo = OneHotEncoder()
geo_encoder = ohe_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [16]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [17]:
ohe_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [18]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=ohe_geo.get_feature_names_out(['Geography']))

In [19]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [21]:
# Combining OHE column with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df],axis=1)

In [22]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [23]:
# saving the Encoders and SScalar

with open('label_encoder_Gender.pkl','wb') as file:
    pickle.dump(label_encoder_Gender, file)


with open('ohe_geo.pkl','wb') as file:
    pickle.dump(ohe_geo, file)

In [24]:
# Dividing the dataset into dependent and independent feature
X=data.drop('Exited', axis=1)
y=data['Exited']

In [25]:
# Spliting the dataset into trainig and testing 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [26]:
#Scaling these features
scaler= StandardScaler()
X_train=  scaler.fit_transform(X_train)
X_test= scaler.fit_transform(X_test)

In [27]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [28]:
#saving these scaler 
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

## ANN Implementaion

In [29]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [31]:
(X_train.shape[1],)

(12,)

In [36]:
## Building Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 connected with input layer
    Dense(32,activation='relu'), ## HL2 
    Dense(1,activation='sigmoid') ##output layer

])

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [40]:
## setting Optimizers and Loss func
import tensorflow
opt=tensorflow.keras.optimizers.legacy.Adam(Learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

TypeError: Unexpected keyword argument passed to optimizer: Learning_rate. Allowed kwargs are {'decay', 'lr', 'global_clipnorm', 'clipnorm', 'clipvalue'}.

In [43]:
## Compiling the Model
model.compile(optimizer="Adam", loss="binary_crossentropy", metrics=['accuracy'])

In [57]:
## Setting up the Tensor Board
log_dir ="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [58]:
## Set up Early Stopping callback

early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10,restore_best_weights=True)

In [59]:
## Training Our Model ANN
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3057 - accuracy: 0.8720 - val_loss: 0.3356 - val_accuracy: 0.8645
Epoch 2/100
250/250 [==============================] - 0s 545us/step - loss: 0.3035 - accuracy: 0.8716 - val_loss: 0.3398 - val_accuracy: 0.8620
Epoch 3/100
250/250 [==============================] - 0s 535us/step - loss: 0.3015 - accuracy: 0.8745 - val_loss: 0.3371 - val_accuracy: 0.8660
Epoch 4/100
250/250 [==============================] - 0s 546us/step - loss: 0.3017 - accuracy: 0.8709 - val_loss: 0.3443 - val_accuracy: 0.8565
Epoch 5/100
250/250 [==============================] - 0s 548us/step - loss: 0.3005 - accuracy: 0.8731 - val_loss: 0.3428 - val_accuracy: 0.8625
Epoch 6/100
250/250 [==============================] - 0s 540us/step - loss: 0.2997 - accuracy: 0.8710 - val_loss: 0.3419 - val_accuracy: 0.8615
Epoch 7/100
250/250 [==============================] - 0s 541us/step - loss: 0.2997 - accuracy: 0.8723 - val_loss: 0.3414 - val_accuracy: 0.8630
Epoch 8/100
250/250 [==============================] - 0s 529us/step - loss: 0.2993 - accuracy: 0.8710 - val_loss: 0.3456 - val_accuracy: 0.8610
Epoch 9/100
250/250 [==============================] - 0s 526us/step - loss: 0.2964 - accuracy: 0.8715 - val_loss: 0.3424 - val_accuracy: 0.8595
Epoch 10/100
250/250 [==============================] - 0s 522us/step - loss: 0.2948 - accuracy: 0.8735 - val_loss: 0.3422 - val_accuracy: 0.8610
Epoch 11/100
250/250 [==============================] - 0s 533us/step - loss: 0.2947 - accuracy: 0.8740 - val_loss: 0.3429 - val_accuracy: 0.8580

In [60]:
model.save('model.h5')

/Users/akash/Desktop/ML Projects/ANN Classification Project/Churn Predictions/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [61]:
# NOW Loading the Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [63]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/akash/Desktop/ML Projects/ANN Classification Project/Churn Predictions/venv/bin/tensorboard", line 5, in <module>
    from tensorboard.main import run_main
  File "/Users/akash/Desktop/ML Projects/ANN Classification Project/Churn Predictions/venv/lib/python3.11/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/akash/Desktop/ML Projects/ANN Classification Project/Churn Predictions/venv/lib/python3.11/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [ ]:
## Now Loading the Pickel file for Prediction